### ISSUE TITLE
Review Literature Review

### ISSUE THREAD

**Issue by emmaredfoot** [emmaredfoot/thesis#1]
I have completed the first 5 chapters of my thesis, through the literature review.  The things I am worried about are that I am setting myself up to not be able to meet the expectations set for a NRHES model.  I also do not set this up to be a major review of the cyclus software yet.  If I come across as too certain that the cyclus model should work, I would appreciate some feedback. The pdf copy of the report should be connected to this issue.
[allocating-heat-electricity (2).pdf](https://github.com/emmaredfoot/thesis/files/1664940/allocating-heat-electricity.2.pdf)

**Comment by TheDoctorRAB** [comment]
See slack.
